#!/bin/bash
#
# Perform necessary testlink setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "whassup" > /tmp/whassup

echo "Thank you for installing testlink!"

exit 0
